"""
Blackbox AI Client — Cloud LLM integration
Provides high-performance AI as the primary provider.
"""
import logging
import json
import time
import requests
from typing import Optional, Any, AsyncGenerator

logger = logging.getLogger(__name__)

class BlackboxClient:
    """Client for Blackbox AI API."""

    def __init__(
        self,
        api_key: str = "sk-ebmAJn7ZlF1YI9Gjkc5ygg",
        model: str = "deepseek-v3", # Blackbox supports deepseek-v3
    ):
        self.api_key = api_key
        self.model = model
        self.base_url = "https://api.blackbox.ai/api/chat"

    async def generate_stream(self, prompt: str, history: list = None) -> AsyncGenerator[str, None]:
        """Yields text chunks as they are generated by Blackbox AI."""
        
        messages = []
        if history:
            # history is formatted as a string in this app, but Blackbox likes list of dicts
            # For simplicity, we'll just pass the prompt as a single user message 
            # with context if we can.
            messages.append({"role": "user", "content": prompt})
        else:
            messages.append({"role": "user", "content": prompt})

        payload = {
            "messages": messages,
            "model": self.model,
            "max_tokens": 1024,
            "stream": True
        }

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        import asyncio
        import queue

        q = queue.Queue()

        def _do_stream():
            try:
                with requests.post(self.base_url, json=payload, headers=headers, stream=True, timeout=30) as resp:
                    if resp.status_code != 200:
                        err_body = resp.text
                        q.put(Exception(f"Blackbox API Status {resp.status_code}: {err_body}"))
                        return
                    
                    for line in resp.iter_lines():
                        if not line:
                            continue
                        
                        line_text = line.decode('utf-8').strip()
                        if line_text.startswith('data: '):
                            data_str = line_text[6:]
                            if data_str == '[DONE]':
                                break
                            try:
                                data_json = json.loads(data_str)
                                choices = data_json.get("choices", [])
                                if choices:
                                    delta = choices[0].get("delta", {})
                                    content = delta.get("content", "")
                                    if content:
                                        q.put(content)
                            except:
                                # Sometimes the stream is just raw text or slightly different format
                                pass
                q.put(None)
            except Exception as e:
                q.put(e)

        loop = asyncio.get_event_loop()
        loop.run_in_executor(None, _do_stream)

        while True:
            item = await asyncio.to_thread(q.get)
            if item is None:
                break
            if isinstance(item, Exception):
                logger.error("Blackbox streaming error: %s", item)
                raise item
            if item:
                yield item

# ── Singleton ─────────────────────────────────────────────────────────────
_blackbox_client: Optional[BlackboxClient] = None

def get_blackbox_client() -> BlackboxClient:
    global _blackbox_client
    if _blackbox_client is None:
        _blackbox_client = BlackboxClient()
    return _blackbox_client
