"""
Ollama Client — Local LLM integration via DeepSeek
Gracefully degrades when Ollama is not running.
"""
import logging
import json
import time
from typing import Optional, Any

from app.ai.llm.prompt_templates import PromptTemplates

logger = logging.getLogger(__name__)


class OllamaClient:
    """Client for local Ollama LLM (phi3:mini)."""

    def __init__(
        self,
        base_url: str = "http://127.0.0.1:11434",
        model: str = "phi3:mini",
    ):
        self.base_url = base_url
        self.model = model
        self._last_check_time = 0
        self._last_check_result = False

    # ── Availability ──────────────────────────────────────────────────────
    @property
    def is_available(self) -> bool:
        """Dynamically check if Ollama is running (cached for 10 seconds)."""
        now = time.time()
        if now - self._last_check_time < 10:
            return self._last_check_result

        import requests
        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=2)
            self._last_check_result = (resp.status_code == 200)
        except Exception:
            self._last_check_result = False
            
        self._last_check_time = now
        return self._last_check_result

    def status(self) -> dict:
        """Return connection status dict for the health endpoint."""
        return {
            "ollama_connected": self.is_available,
            "model": self.model,
            "base_url": self.base_url,
        }

    async def generate(self, prompt: str, system_prompt: str = None) -> Optional[str]:
        if not self.is_available:
            return None
        try:
            import asyncio
            import requests

            payload = {
                "model": self.model,
                "prompt": prompt,
                "system": system_prompt or PromptTemplates.system_prompt(),
                "stream": False,
                "keep_alive": -1,
                "options": {
                    "temperature": 0.7,
                    "top_p": 0.9,
                    "num_predict": 512,
                    "num_ctx": 4096,
                },
            }

            def _do_post():
                resp = requests.post(
                    f"{self.base_url}/api/generate",
                    json=payload,
                    timeout=300,
                )
                if resp.status_code == 200:
                    return resp.json().get("response")
                return None

            return await asyncio.to_thread(_do_post)

        except Exception as e:
            err_msg = f"INTERNAL_ERROR: {type(e).__name__} - {str(e)}"
            logger.error("Ollama generation error: %s", err_msg)
            return err_msg

    async def generate_stream(self, prompt: str, system_prompt: str = None):
        """Yields text chunks as they are generated by the LLM natively."""
        if not self.is_available:
            yield "INTERNAL_ERROR: AI Engine Offline."
            return

        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system_prompt or PromptTemplates.system_prompt(),
            "stream": True,
            "keep_alive": -1,
            "options": {
                "temperature": 0.7,
                "top_p": 0.9,
                "num_predict": 1024,
                "num_ctx": 4096,
            },
        }

        import asyncio
        import requests
        import json
        import queue

        q = queue.Queue()

        def _do_stream():
            try:
                with requests.post(f"{self.base_url}/api/generate", json=payload, stream=True, timeout=300) as resp:
                    if resp.status_code != 200:
                        q.put(Exception(f"Status {resp.status_code}"))
                        return
                    for line in resp.iter_lines():
                        if line:
                            decoded = json.loads(line.decode('utf-8'))
                            q.put(decoded.get("response", ""))
                            if decoded.get("done"):
                                break
                q.put(None)
            except Exception as e:
                q.put(e)

        loop = asyncio.get_event_loop()
        loop.run_in_executor(None, _do_stream)

        while True:
            item = await asyncio.to_thread(q.get)
            if item is None:
                break
            if isinstance(item, Exception):
                yield f"\n\n[INTERNAL_ERROR: {str(item)}]"
                break
            if item:
                yield item

    # ── Enhance template response with LLM ────────────────────────────────
    async def enhance_response(
        self,
        user_message: str,
        intent: str,
        data: Any,
        history: str = "",
    ) -> Optional[str]:
        if not self.is_available:
            return None

        summary = "No matching database results."
        # Summarise data for the prompt
        if data:
            if isinstance(data, list):
                summary = f"Found {len(data)} tenders.\n"
                count = 1
                for t in data:
                    if count > 3:
                        break
                    if isinstance(t, dict):
                        summary += (
                            f"{count}. {t.get('title','N/A')} | Source: {t.get('source','?')} "
                            f"| Deadline: {t.get('end_date','?')}\n"
                        )
                    count += 1
            elif isinstance(data, dict):
                summary = json.dumps(data, indent=2, default=str)[:600]
            else:
                summary = str(data)[:500]

        prompt = (
            f"You are Leonex AI, an expert, professional assistant for the TENDER platform.\n"
            f"Respond directly to the user's message. Format clearly using Markdown. Do not expose internal technical reasoning.\n\n"
            f'User asked: "{user_message}"\n'
            f"Conversation so far:\n{history[-400:]}\n\n"
            f"Database context:\n{summary}\n"
        )
        
        import re
        result = await self.generate(prompt)
        if result and len(result) > 4:
            # Strip out DeepSeek's <think>...</think> chain of thought tags
            clean_result = re.sub(r'<think>.*?</think>', '', result, flags=re.DOTALL).strip()
            return clean_result
        return None


# ── Singleton ─────────────────────────────────────────────────────────────
_ollama_client: Optional[OllamaClient] = None


def get_ollama_client() -> OllamaClient:
    global _ollama_client
    if _ollama_client is None:
        _ollama_client = OllamaClient()
    return _ollama_client